// src/data/mockStudents.js
export const allStudents = [
  {
    key: '1',
    fullName: 'Alice Johnson',
    school: 'Springfield High',
    grade: '10',
    section: 'A',
    email: 'alice@school.com',
  },
  {
    key: '2',
    fullName: 'Bob Williams',
    school: 'Springfield High',
    grade: '10',
    section: 'B',
    email: 'bob@school.com',
  },
  {
    key: '3',
    fullName: 'Charlie Brown',
    school: 'Lincoln Middle',
    grade: '9',
    section: 'A',
    email: 'charlie@school.com',
  },
  {
    key: '4',
    fullName: 'Diana Prince',
    school: 'Lincoln Middle',
    grade: '11',
    section: 'C',
    email: 'diana@school.com',
  },
  {
    key: '5',
    fullName: 'Edward Norton',
    school: 'Springfield High',
    grade: '11',
    section: 'A',
    email: 'edward@school.com',
  },
  {
    key: '6',
    fullName: 'Fiona Gallagher',
    school: 'Lincoln Middle',
    grade: '9',
    section: 'B',
    email: 'fiona@school.com',
  },
  {
    key: '7',
    fullName: 'George Costanza',
    school: 'Springfield High',
    grade: '12',
    section: 'A',
    email: 'george@school.com',
  },
  {
    key: '8',
    fullName: 'Hannah Baker',
    school: 'Lincoln Middle',
    grade: '12',
    section: 'C',
    email: 'hannah@school.com',
  },
];