// src/data/mockStudents.js
export const allStudents = [
  {
    key: '1',
    fullName: 'Alice Johnson',
    school: 'Springfield High',
    email: 'alice@school.com',
    plan: "Pro",
    amount: 20,
    status: "paid",
    date: "2026-04-20",
    transactionId: "TXN123456",
  },
  {
    key: '2',
    fullName: 'Bob Williams',
    school: 'Springfield High',
    email: 'bob@school.com',
    plan: "Pro",
    amount: 20,
    status: "paid",
    date: "2026-04-20",
    transactionId: "TXN123457",
  },
  {
    key: '3',
    fullName: 'Charlie Brown',
    school: 'Lincoln Middle',
    email: 'charlie@school.com',
    plan: "Pro",
    amount: 20,
    status: "paid",
    date: "2026-04-20",
    transactionId: "TXN123458",
  },
  {
    key: '4',
    fullName: 'Diana Prince',
    school: 'Lincoln Middle',
    email: 'diana@school.com',
    plan: "Pro",
    amount: 20,
    status: "paid",
    date: "2026-04-20",
    transactionId: "TXN123459",
  },
  {
    key: '5',
    fullName: 'Edward Norton',
    school: 'Springfield High',
    email: 'edward@school.com',
    plan: "Pro",
    amount: 20,
    status: "paid",
    date: "2026-04-20",
    transactionId: "TXN123460",
  },
  {
    key: '6',
    fullName: 'Fiona Gallagher',
    school: 'Lincoln Middle',
    email: 'fiona@school.com',
    plan: "Pro",
    amount: 20,
    status: "paid",
    date: "2026-04-20",
    transactionId: "TXN123461",
  },
  {
    key: '7',
    fullName: 'George Costanza',
    school: 'Springfield High',
    email: 'george@school.com',
    plan: "Pro",
    amount: 20,
    status: "paid",
    date: "2026-04-20",
    transactionId: "TXN123462",
  },
  {
    key: '8',
    fullName: 'Hannah Baker',
    school: 'Lincoln Middle',
    email: 'hannah@school.com',
    plan: "Pro",
    amount: 20,
    status: "paid",
    date: "2026-04-20",
    transactionId: "TXN123463",
  },
];